### ISSUE TITLE
Steam Pages No Longer Render

### ISSUE THREAD

**Issue by encrypt3d-shadow** [AikoMidori/steam-dark-mode#3]
Any webpages inside of the Steam client (Store, Community, and Profile) are blank when I go to them. Sometimes I can temporarily fix it by reinstalling the dark mode theme, but even that isn't a guaranteed fix. This seems to occur on its own, independent of PC or Steam updates. The only way I can really use any part of Steam other than the library is in my browser. Oddly enough, the "Steam News" window that pops up works fine, and going to the store while it's open will display the store in there.

**Comment by Plaer1** [comment]
I'm working on a patch right now to fix this actually :)

**Comment by PhantomGamers** [comment]
The reason this happens is that Steam's CSS parser no longer handles files larger than 31KB properly. @Plaer1's newest updates might reduce the likelihood of it breaking for you, so definitely give it a try now, but for me it's still completely broken (I'm not sure why, but the issue seems more severe for me than for others).

I just pushed PR #9 which adds a new Hard Edges Lite variant which is smaller than 31KB, if the newest regular version or normal hard edges version still don't work for you, that one should.

We'd definitely appreciate feedback on both fronts though! Please let us know if either solution works for you, or if neither does so that we can continue working on it!

**Comment by PhantomGamers** [comment]
> The same issue happened again, and updating the skin didn't fix it.

The Hard Edges Lite variant should remedy the problem.

**Comment by Plaer1** [comment]
> > The same issue happened again, and updating the skin didn't fix it.
> 
> The Hard Edges Lite variant should remedy the problem.

I just came here to say this lol.

**Comment by DessertArbiter** [comment]
i had this same issue but i was able to fix it by disabling gpu acceleration for web views
![image](https://user-images.githubusercontent.com/12720300/62984273-93c5c500-be00-11e9-8b07-381ee42070fd.png)

**Comment by encrypt3d-shadow** [comment]
I caved and used hard edges lite. It doesn't have the nice rounded images,
but it still looks good (and worlds better than Steam's site.

**Comment by AikoMidori** [comment]
Both of the Webkits have been update to the latest version and work
